DROP TABLE IF EXISTS METER_READINGS;
DROP TABLE IF EXISTS METERS;

CREATE TABLE IF NOT EXISTS METERS (
    id text PRIMARY KEY UNIQUE NOT NULL,
    meter_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS METER_READINGS (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    meter_id text NOT NULL REFERENCES METERS(id) ON DELETE CASCADE,
    reading DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
