DROP TABLE METERS;
DROP TABLE METER_READINGS;

CREATE TABLE IF NOT EXISTS METERS (
    id SMALLINT NOT NULL,
    "name" char[50] NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS METER_READINGS (
    id SERIAL PRIMARY KEY,
    meter_id SMALLINT NOT NULL REFERENCES METERS(id) ON DELETE CASCADE,
    reading DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
